package myjavapackage.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import com.github.manosbatsis.scrudbeans.api.mdd.annotation.model.ScrudBean;
import com.github.manosbatsis.scrudbeans.jpa.model.AbstractAutoGeneratedLongPersistable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

/**
 * Sample entity model to test validation of non-null or unique @Column constraints
 */
@Entity
@Table(name = "discount_code")
@ScrudBean
@ApiModel(value = "DiscountCode", description = "A model representing an discount code")
@Data
public class DiscountCode extends AbstractAutoGeneratedLongPersistable {

    @NotNull
    @Column(nullable = false, unique = true)
    @ApiModelProperty(value = "The discount code", required = true)
    private String code;

    @NotNull
    @Column(nullable = false)
    @ApiModelProperty(value = "The discount percentage", required = true)
    private Integer percentage;
}
